Add variable version of News message
mozilla-l10n/fx-private-relay-l10n pull request #64
Opened 2022-03-02 14:54 UTC by Vinnl

Some upstream limits might be preventing us from hitting 25MB in
one go, so we might need to modify this message.

2022-03-02 16:22 UTC, peiying2 requested changes
Variable comments don't match how they are used in the strings.

2022-03-02 16:22 UTC, peiying2 commented on en/app.ftl
> +# Variables:
The comments on the variables don't match with those used in the string.

2022-03-02 16:22 UTC, peiying2 commented on en/app.ftl
> +# Variables:
The comments on the variables don't match with those used in the string.

2022-03-02 16:27 UTC, Vinnl commented
@peiying2 Apologies, I misunderstood how this worked in other strings. Removed the incorrect comments!

2022-03-03 20:25 UTC, peiying2 approved these changes

2022-03-03 20:43 UTC, merged