Add strings for the tracker removal setting
mozilla-l10n/fx-private-relay-l10n pull request #91
Opened 2022-06-10 08:59 UTC by Vinnl

These are strings for the UI to enable/disable tracker removal in the settings page. Please do not merge this yet; there are more tracker removal-related strings to land.

![image](https://user-images.githubusercontent.com/4251/173029794-a347481e-c9e8-4758-a4a2-19457140ba3e.png)

![image](https://user-images.githubusercontent.com/4251/173029815-91446b47-824f-4ffa-a2fe-f6752a9e2231.png)

2022-06-10 15:05 UTC, peiying2 approved these changes

2022-06-20 15:09 UTC, Vinnl commented
@peiying2 I just added the rest of the strings!

Some screenshots:

![image](https://user-images.githubusercontent.com/4251/174631614-6ce4944a-ec94-4667-95e5-c29b390417e9.png)

![image](https://user-images.githubusercontent.com/4251/174631674-6f9b82f4-00dd-4390-a7b2-6ecc548cde39.png)

![image](https://user-images.githubusercontent.com/4251/174631710-d775afeb-efb3-45a6-8034-40b4052ef84a.png)

![image](https://user-images.githubusercontent.com/4251/174631771-b99e35e4-717b-4908-950f-6b3b93ee0db5.png)

![image](https://user-images.githubusercontent.com/4251/174631804-b2c84b0f-e74b-421f-864a-e8cf89c68323.png)

2022-06-22 17:13 UTC, peiying2 requested changes
Minor issues:
- stylistic on category names, capital initial for all? `Tracker removal` appears to be different from the others
- punctuation (how conditional clause is used)
- `-` n dash or hyphen.

2022-06-22 17:13 UTC, peiying2 commented on en/app.ftl
> +trackerreport-breakage-warning = Important: Sometimes removing trackers may cause your email to look broken, because the trackers are often contained within images, which will not load if they contai
Remove the comma before `because…`

2022-06-23 12:23 UTC, Vinnl commented on en/app.ftl
> +profile-label-trackers-removed = Trackers removed
I think so, good eye! 6c0a6cb

2022-06-23 12:25 UTC, Vinnl commented on en/app.ftl
> +faq-question-bulk-trackerremoval-answer = You can only turn tracker removal on at an account level—it either removes trackers from all of your emails, or none of them.
b011408

2022-06-23 15:53 UTC, peiying2 commented on en/app.ftl
> +profile-indicator-tracker-removal-alt = Tracker removal
Ah, I see. So where does this string appear? 
![image](https://user-images.githubusercontent.com/6090393/175341958-480b5726-6163-4ef6-bc57-31617d7db702.png)

2022-06-24 13:35 UTC, Vinnl commented on en/app.ftl
> +trackerreport-breakage-warning = Important: Sometimes removing trackers may cause your email to look broken, because the trackers are often contained within images, which will not load if they contai
9913d3d

2022-06-24 13:37 UTC, Vinnl commented on en/app.ftl
> +profile-indicator-tracker-removal-alt = Tracker removal
Chris came up with an alternative: 95a57f0

The "Trackers removed" in your screenshot is `profile-label-trackers-removed`.

2022-06-24 16:12 UTC, peiying2 commented on en/app.ftl
> +
this change seems to introduce an error? See the commit with an `x` status (the last of a series of commits). Is it the line break breaks the section under `## Mobile menu text`? Not sure.

2022-06-24 16:52 UTC, peiying2 commented
@Vinnl Take a look of this file and identify the issues that failed linter:

1) https://github.com/mozilla-l10n/fx-private-relay-l10n/blob/3e79fa545a05c86d6e1327dbde5e66de588ad19b/en/app.ftl#L494. You have an extra line break before the ## comment. Should be just one line space.

2) https://github.com/mozilla-l10n/fx-private-relay-l10n/blob/3e79fa545a05c86d6e1327dbde5e66de588ad19b/en/app.ftl#L826 - notice the string ID contains `_` rather than `-`.

2022-06-24 16:54 UTC, peiying2 requested changes
The linter script will show the types of problems that failed the check: https://github.com/mozilla-l10n/moz-fluent-linter/blob/main/src/fluent_linter/linter.py. I commented on where the issues are. Please make changes accordingly. Thank you!

2022-06-27 00:08 UTC, Vinnl commented
Thanks for explaining the linter errors @peiying2, fixed in 76a5f5f.

2022-06-27 15:33 UTC, peiying2 approved these changes
LGTM!!

2022-06-28 00:40 UTC, Vinnl commented
Thanks for all the improvements @peiying2!

2022-06-28 00:40 UTC, merged